name: build-and-publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./src/MemoryMonitor.csproj

      - name: Build
        run: dotnet build ./src/MemoryMonitor.csproj -c Release --no-restore

      - name: Publish (framework-dependent)
        run: dotnet publish ./src/MemoryMonitor.csproj -c Release -o out --no-restore

      - uses: actions/upload-artifact@v4
        with:
          name: MemoryMonitor-${{ runner.os }}
          path: out
